name: autofix.ci
on:
  pull_request:
  push:
    branches: [main, beta]
jobs:
  autofix:
    if: ${{ github.repository_owner == 'recap-utr' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
        with:
          extra-conf: |
            accept-flake-config = true
            log-lines = 1000
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: recap
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix fmt
      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
        with:
          commit-message: "chore: reformat code"
