on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'recap-utr' && github.event_name == 'push' }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - uses: cihelper/action-semanticrelease-npm@v1
        id: semanticrelease
      - run: nix run .#dockerManifest --impure
        if: ${{ steps.semanticrelease.outputs.released == 'true' }}
        env:
          VERSION: ${{ steps.semanticrelease.outputs.version }}
          GH_TOKEN: ${{ github.token }}
